[workspace]
resolver = "2"
members = [
    "crates/office-document",
    "crates/office-commands",
]

[workspace.package]
edition = "2024"
license = "AGPL-3.0-or-later"
rust-version = "1.85"
version = "0.1.0-dev.1"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
